apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: traefik

resources:
- values.yaml
- traefik-ingress.yaml

helmCharts:
  - name: traefik
    namespace: traefik
    releaseName: traefik
    repo: https://traefik.github.io/charts