apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cloudflared


helmCharts:
  - name: cloudflared
    namespace: cloudflared
    valuesFile: values.yaml
    releaseName: cloudflare-tunnel-remote
    repo: https://cloudflare.github.io/helm-charts
