apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cloudflared


helmCharts:
  - name: cloudflare-tunnel-remote
    namespace: cloudflared
    valuesFile: values.yaml
    releaseName: cloudflared
    repo: https://cloudflare.github.io/helm-charts
