apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: datadog

resources:
  - namespace.yaml

helmCharts:
  - name: datadog
    namespace: datadog
    valuesFile: datadog-values.yaml
    releaseName: datadog
    version: latest
    repo: https://helm.datadoghq.com
